# Generated by Django 5.1.6 on 2025-04-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_image1_comment_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image1_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/compressed/', verbose_name='сжатое изображение 1'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image2_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/compressed/', verbose_name='сжатое изображение 2'),
        ),
    ]
