# Generated by Django 5.1.6 on 2025-04-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_image1_compressed_comment_image2_compressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/', verbose_name='изображение 1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image1_compressed',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/compressed/', verbose_name='сжатое изображение 1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/', verbose_name='изображение 2'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image2_compressed',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/compressed/', verbose_name='сжатое изображение 2'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='текст комментария'),
        ),
    ]
