# Generated by Django 5.1.6 on 2025-04-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_created_at_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image1_compressed',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image2_compressed',
        ),
    ]
