# Generated by Django 5.1.6 on 2025-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', verbose_name='изображение 1'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', verbose_name='изображение 2'),
        ),
    ]
