# Generated by Django 5.1.6 on 2025-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_country_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar image.', max_length=500, null=True, upload_to='user_avatars/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_compressed',
            field=models.ImageField(blank=True, help_text='Compressed version of the user avatar.', max_length=500, null=True, upload_to='user_avatars/compressed/', verbose_name='compressed avatar'),
        ),
    ]
