# Generated by Django 5.1.6 on 2025-04-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_avatar_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version of the user avatar.', max_length=500, null=True, upload_to='user_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail_compressed',
            field=models.ImageField(blank=True, help_text='Compressed version of the thumbnail.', max_length=500, null=True, upload_to='user_thumbnails/compressed/', verbose_name='compressed thumbnail'),
        ),
    ]
