# Generated by Django 5.1.6 on 2025-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_thumbnail_user_thumbnail_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Brief information about the user.', null=True, verbose_name='about'),
        ),
    ]
