# Generated by Django 5.1.6 on 2025-04-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_compressed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thumbnail_compressed',
        ),
    ]
