# Generated by Django 5.1.6 on 2025-04-30 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_remove_user_avatar_remove_user_avatar_compressed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_avatar', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='user_avatars/', verbose_name='avatar')),
                ('avatar_compressed', models.ImageField(blank=True, max_length=500, null=True, upload_to='user_avatars/compressed/', verbose_name='compressed avatar')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='user_thumbnails/', verbose_name='thumbnail')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'db_table': 'user_avatars',
            },
        ),
    ]
