# Generated by Django 5.1.6 on 2025-04-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_main_images', '0001_initial'),
        ('recipes', '0003_remove_recipe_main_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemainimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipemainimage',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='main_image_info', serialize=False, to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
