# Generated by Django 5.1.6 on 2025-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='image_url',
        ),
        migrations.AddField(
            model_name='instruction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/instruction_recipe_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='image_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/instruction_recipe_images_compressed/', verbose_name='Сжатое изображение'),
        ),
    ]
