# Generated by Django 5.1.6 on 2025-04-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_alter_instruction_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='image_compressed',
        ),
    ]
