# Generated by Django 5.1.6 on 2025-04-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_remove_instruction_image_and_more'),
        ('recipes', '0002_alter_recipe_main_picture_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instruction',
            constraint=models.UniqueConstraint(fields=('recipe', 'step_number'), name='unique_recipe_step'),
        ),
    ]
