# Generated by Django 5.1.6 on 2025-04-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instruction',
            table='instructions',
        ),
    ]
