# Generated by Django 5.1.6 on 2025-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_remove_instruction_image_url_instruction_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='recipe_images/instruction_recipe_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='image_compressed',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='recipe_images/instruction_recipe_images_compressed/', verbose_name='Сжатое изображение'),
        ),
    ]
