# Generated by Django 5.1.6 on 2025-04-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_main_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='main_picture',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='main_picture_compressed',
        ),
    ]
