# Generated by Django 5.1.6 on 2025-03-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('status', models.CharField(choices=[('moderating', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонен')], default='draft', max_length=16, verbose_name='статус модерации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.user', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'db_table': 'recipes',
            },
        ),
    ]
