# Generated by Django 5.1.6 on 2025-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_picture',
            field=models.ImageField(blank=True, help_text='Основное изображение рецепта', max_length=500, null=True, upload_to='recipe_images/main_recipe_images/', verbose_name='основное изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_picture_compressed',
            field=models.ImageField(blank=True, help_text='Сжатая версия основного изображения рецепта', max_length=500, null=True, upload_to='recipe_images/main_recipe_images_compressed/', verbose_name='сжатое основное изображение'),
        ),
    ]
