# Generated by Django 5.1.6 on 2025-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(blank=True, null=True, verbose_name='инструкция'),
        ),
    ]
