# Generated by Django 5.1.6 on 2025-04-30 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructions', '0004_remove_instruction_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='recipe_images/instruction_recipe_images/', verbose_name='Изображение')),
                ('image_compressed', models.ImageField(blank=True, max_length=500, null=True, upload_to='recipe_images/instruction_recipe_images_compressed/', verbose_name='Сжатое изображение')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instructions.instruction', verbose_name='Инструкция')),
            ],
            options={
                'db_table': 'instruction_images',
            },
        ),
    ]
