# Generated by Django 5.1.6 on 2025-04-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionimage',
            options={'verbose_name': 'Изображение инструкции', 'verbose_name_plural': 'Изображения инструкций'},
        ),
    ]
