# Generated by Django 5.1.6 on 2025-04-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction_images', '0002_alter_instructionimage_options'),
        ('instructions', '0005_instruction_unique_recipe_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='instructionimage',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='images', serialize=False, to='instructions.instruction', verbose_name='Инструкция'),
        ),
    ]
