# Generated by Django 5.1.6 on 2025-04-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0006_remove_comment_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/', verbose_name='изображение 1')),
                ('image2', models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/', verbose_name='изображение 2')),
                ('image1_compressed', models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/compressed/', verbose_name='сжатое изображение 1')),
                ('image2_compressed', models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_images/compressed/', verbose_name='сжатое изображение 2')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images_info', to='comments.comment', verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'изображения комментария',
                'verbose_name_plural': 'изображения комментариев',
                'db_table': 'comment_images',
            },
        ),
    ]
