# Generated by Django 5.1.6 on 2025-04-30 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_images', '0001_initial'),
        ('comments', '0006_remove_comment_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimages',
            name='id',
        ),
        migrations.AlterField(
            model_name='commentimages',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='images_info', serialize=False, to='comments.comment', verbose_name='комментарий'),
        ),
    ]
